import CCol from './Grid/Col'
import CRow from './Grid/Row'
import Provider, { tokens } from './theme'

export const theme = tokens
export const ComponentsProvider = Provider
export const Row = CRow
export const Col = CCol

export { Alert } from './Alert'
export { Avatar } from './Avatar'
export { Box } from './Box'
export { Breadcrumb } from './Breadcrumb'
export { Button } from './Button/Button'
export { Buttons } from './Button/Buttons'
export { CardAddress } from './CardAddress'
export { CardBlog } from './CardBlog'
export { CardProduct } from './CardProduct'
export { Checkbox } from './Checkbox'
export { Collapse } from './Collapse/Collapse'
export { CollapseItem } from './Collapse/CollapseItem'
export { CookieConsent } from './CookieConsent'
export { Icon } from './Icon'
export { NewIcon } from './Icon/NewIcon'
export { IconsList } from './Icon/IconsList'
export { Input } from './Input'
export { HorizontalScroll } from './HorizontalScroll'
export { Link } from './Link'
export { List } from './List/List'
export { ListItem } from './List/ListItem'
export { LinearGradient } from './LinearGradient'
export { Loader } from './Loader'
export { Logo } from './Logo'
export { Modal } from './Modal'
export { Placeholder } from './Placeholder'
export { RatingStar } from './Rating'
export { Select } from './Select'
export { SelectCard } from './SelectCard'
export { Tag } from './Tag'
export { Text } from './Text'
export { Textarea } from './Textarea'
export { Tooltip } from './Tooltip'
export { User } from './User'
